spring:
  profiles:
    active: @spring.profiles.active@
  datasource:
    url: jdbc:h2:mem:mydb
    username: root
    password:
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc.batch_size: 10
        order_inserts: true
  h2:
    console:
      enabled: true
      path: /h2